### ISSUE TITLE
Regression: Cannot format specific folder anymore, only entire workspace

### ISSUE THREAD

**Issue by JonathanWolfe** [jbockle/format-files#18]
In v3.0.0 you could right click a folder and format all it's contents, but now in 3.1.2 you can only format the entire workspace.

**Comment by HEBOS** [comment]
Same with me

**Comment by oestrogen** [comment]
Same here

**Comment by samuelyhsu** [comment]
Same with me

**Comment by Rainy-Bear** [comment]
I think It was a very wrong decision to remove the formatted folder feature

**Comment by centigrade-thomas-becker** [comment]
If this issue affects you then please use the 👍 in the original post instead of posting a comment.

How is it possible to revert this extension to an older version that works?
