### ISSUE TITLE
"formatFiles.extensionsToInclude" seems not work properly in v3.1.2

### ISSUE THREAD

**Issue by samuelyhsu** [jbockle/format-files#22]
Only origin "*" could work, if I use "c,h,cpp,hpp" instead, it won't match or only match one file. 

This is a great tool. Thank you for your effort.

**Comment by leowu2017** [comment]
it can be set for only one extension in this version, e.g., "c", or "h".

**Comment by HpLightcorner** [comment]
I came accross the same issue - you would have to add curly braces so that the extensions are working.... like `"{c,h,cpp,hpp}"` - I opened a PR as I think the behaviour is not so obvious....

**Comment by jbockle** [comment]
updated in #27, thanks @HpLightcorner
