### ISSUE TITLE
The setting is not applied after saving setting.json in v3.1.2

### ISSUE THREAD

**Issue by leowu2017** [jbockle/format-files#24]
The setting won't be applied if it is saved directly in the editor. VSCode has to be reopened to apply the changed settings.

**Comment by HpLightcorner** [comment]
I came across the same issue - the configuration seems to be loaded only once when the extensions is instantiated. I opened a PR to fix the issue by simply loading the config every time a Format Files command is called.

**Comment by jbockle** [comment]
fixed in #26, thanks @HpLightcorner
