### ISSUE TITLE
Html files skipped

### ISSUE THREAD

**Issue by MrJacquers** [jbockle/format-files#38]
Useful extension, but it skips certain files like .html in my Angular project.

I've updated the settings, but html files are still skipped. CSS files as well.

"formatAll.includeFileExtensions": [
        ".ts",
        ".json",
        ".html"
    ]

**Comment by jbockle** [comment]
can you find the format files output window and copy/paste the logs here

**Comment by MrJacquers** [comment]
> can you find the format files output window and copy/paste the logs here

Where can I find this?

**Comment by jbockle** [comment]
after running the format files command go to the output panel then select the "Format Files" output in the dropdown

![image](https://user-images.githubusercontent.com/6231457/143977962-1f899582-915b-4dfc-ae91-1db335a0d70d.png)

**Comment by MrJacquers** [comment]
I couldn't find that output log, but I managed to edit the settings, restart VS Code and it's working now :)
