### ISSUE TITLE
Support for format of git checkout files

### ISSUE THREAD

**Issue by oavitzur** [jbockle/format-files#40]
Hi
Your extenstion is super cool, I needed support to format only git checked out files in my workspace so I added that support to your extenstion. 
Let me know if this interests you and how I can open a pull request for it ?
Thanks!

**Comment by jbockle** [comment]
hi @oavitzur, sounds interesting! Please check out a guide on how to contribute to a github open source project such as:
- https://github.com/firstcontributions/first-contributions
- https://www.dataschool.io/how-to-contribute-on-github/
