### ISSUE TITLE
How to ignore a folder name on any folder level?

### ISSUE THREAD

**Issue by Spenhouet** [jbockle/format-files#43]
With python I have a `__pycache__` folder on most folder levels and I would like to ignore all of them.

I tried:
```
"formatFiles.excludedFolders": [
        ".vscode",
        ".git",
        ".mypy_cache",
        "__pycache__"
    ],
```

but this does not work.
I tried adding wildcards, but no luck either.
Also tried the same with the `excludePattern` option.

**Comment by jbockle** [comment]
if you use `excludePattern`, you can specify glob patterns to skip specific folders at any depth

e.g. to exclude all `.vscode` and `.git` try `"excludePattern": "**/.vscode/**/*,**/.git/**/*"`

**Comment by Spenhouet** [comment]
Thanks, this worked. I tried the wrong syntax for the wildcard (regex syntax).
