### ISSUE TITLE
Does not run Organize Imports

### ISSUE THREAD

**Issue by snebjorn** [jbockle/format-files#5]
I noticed that after having run "FormatFiles" my TypeScript imports would be rearranged when saving the file.

I have this option enabled:
```
  "editor.codeActionsOnSave": {
    "source.organizeImports": true
  }
```

Example:

Result after "FormatFiles"
```
import {
  Directive,
  HostListener,
  Input,
  Output,
  EventEmitter
} from "@angular/core";
```
Result after manually saving the file
```
import {
  Directive,
  EventEmitter,
  HostListener,
  Input,
  Output
} from "@angular/core";
```

**Comment by jbockle** [comment]
This should work now
