### ISSUE TITLE
Suggestion: Make "Cancel formatting" more accessible

### ISSUE THREAD

**Issue by centigrade-thomas-becker** [jbockle/format-files#6]
When format-files is running the status bar offers a button "Cancel formatting". The full output looks something like this:

```
[Spinner icon] formatting documents: Formatting [path name] [Workspace] Cancel formatting
```

However, it is really hard to actually click on "Cancel formatting" because its position constantly changes based on how long [path name] is. 

Suggestion: Move the button to the left of [path name], so that its position is fixed.

**Comment by jbockle** [comment]
Thanks for the suggestion-at the time I wrote this extension, vscode APIs were limited and didn't give me much option, but its gotten a lot better.  Version 2.0 just released and now includes this!
